project:
  name: Retail_ETL_Framework

audit:
  enabled: true
  path: /Volumes/retail_catalog/audit/audit

reject:
  enabled: true
  path: /Volumes/retail_catalog/reject/reject
  

sources:

  customer:

    input_path: /Volumes/retail_catalog/input/input_files/customer_master_15000_rows.csv

    bronze_path: /Volumes/retail_catalog/bronze/customer

    silver_path: /Volumes/retail_catalog/silver/customer_vol

    gold_path: /Volumes/retail_catalog/gold/customer360_vol

    business_key:
      - customer_id

    order_column: updated_date

    record_source: CRM

    output_format: parquet

    write_mode: overwrite

    customer_name_column: customer_name

    partition_columns:
      - ingestion_date

    standardize_columns:
      customer_name: name


  sales:

    input_path: /Volumes/retail_catalog/input/sales_fact_15000_rows.csv

    bronze_path: /Volumes/retail_catalog/bronze/sales

    silver_path: /Volumes/retail_catalog/silver/sales

    business_key:
      - order_id

    order_column: updated_date

    record_source: POS